name: violet
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'
version: 1.0.0+1

msix_config:
  display_name: Violet
  publisher_display_name: Your Name
  identity_name: com.gfdg.myapp
  msix_version: 1.0.0.0
  logo_path: assets/images/branding/logo.png


environment:
  sdk: ^3.10.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  window_size: ^0.1.0

  # State management
  get: ^4.7.3

  # file picker
  image_picker: ^1.2.1
  file_picker: ^10.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.6


  flutter_launcher_icons: ^0.14.4

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/branding/logo.png" # your icon image path


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
      - assets/images/
      - assets/images/branding/
      - assets/icons/
      - assets/icons/future_icon/

